docs/LEARNING.md
Added some learning resources to start with. The Julia website already has an updated list of resources, so it mostly just links to that.
=> Documentation: learning resources

README.md
=> Add code formatting guidelines & typo fixes

exercises/atbash-cipher/runtests.jl
Hard tabs happened somehow, why!
=> Fix atbash-cipher test sets indentation

config.json, exercises/hello-world/example.jl, exercises/hello-world/runtests.jl
Update according to https://github.com/exercism/x-common/pull/544
Please don't merge this until the date mentioned in the PR above.
=> hello-world: Update to fit the new canonical data

docs/ABOUT.md, docs/INSTALLATION.md, docs/RESOURCES.md
This adds documentation to the about, installation and resources sections.
Feedback would be very much appreciated, especially for `ABOUT.md`. I'm not quite sure if this fits what is expected for that section.
=> RFC: Add track documentation

exercises/custom-set/HINTS.md, exercises/custom-set/runtests.jl
I accidentally left some todo-comments in the testsuite, this removes them.
Also added a hint and example that demonstrates that operators are functions in Julia.
=> custom-set: Additional hint & testsuite clean-up

.travis.yml
https://discourse.julialang.org/t/julia-0-6-alpha-released-please-update-your-projects/2571
=> Add v0.6-alpha to Travis tests; remove v0.5.0 test

config.json, exercises/complex-numbers/HINTS.md, exercises/complex-numbers/example.jl, exercises/complex-numbers/runtests.jl
This implements https://github.com/exercism/x-common/pull/718
The PR above has to be merged before this one can be merged. This also requires v0.6.
=> Add exercise: Complex numbers

config.json, exercises/grains/README.md, exercises/grains/example.jl, exercises/grains/grains.jl, exercises/grains/runtests.jl
Contributes to exercism/julia#87. Loosely based on [Python implementation](https://github.com/exercism/python/tree/master/exercises/grains).
=> Implement Grains exercise

config.json, exercises/run-length-encoding/README.md, exercises/run-length-encoding/example.jl, exercises/run-length-encoding/run-length-encoding.jl, exercises/run-length-encoding/runtests.jl
=> Add exercise: run-length-encoding

config.json, exercises/triangle/README.md, exercises/triangle/example.jl, exercises/triangle/runtests.jl, exercises/triangle/triangle.jl
This question has been marked with the topic `mathematics`, but to be able to fully make use of the mathematical beauty of this question, a good understanding of how to chop up the procedure into smaller parts is necessary. So I add in `functional abstraction` too.
=> Add exercise: triangle

config.json
Based on discussions on Slack, this should better be a side exercise for now. Mentoring it is quite challenging and time consuming and there are some annoyances with `≈` that can come up that can make the bonus tasks unnecessarily complicated.
=> Change complex-numbers to side exercise

exercises/grains/example.jl, exercises/grains/runtests.jl
=> replaced grains tests with canonical-data tests and fixed example script

config.json, exercises/minesweeper/README.md, exercises/minesweeper/example.jl, exercises/minesweeper/minesweeper.ipynb, exercises/minesweeper/runtests.jl
This add a new exercise specified at
https://github.com/exercism/problem-specifications/tree/master/exercises/minesweeper.
=> Add minesweeper exercise

config.json, exercises/allergies/README.md, exercises/allergies/allergies.ipynb, exercises/allergies/allergies.jl, exercises/allergies/example.jl, exercises/allergies/runtests.jl
I hope everything's gone well
I'm open to suggestions
=> Add the allergies exercise

config.json
* Preparation for Exercism Research Experiment 1
* See https://github.com/exercism/ruby/pull/1016 for details
=> Add editor settings to config.json

config/maintainers.json
I've committed some stuff now, so let's be less shy.
=> Show Colin Caine as a maintainer

bin/fetch-configlet, bin/fetch-configlet.ps1
It's borked and breaking the ["Progression diff" workflow process](https://github.com/exercism/julia/actions?query=workflow%3A%22Progression+diff%22). An upstream update fixed it: https://github.com/exercism/configlet/commit/c70be6269e71512ef0c041644f2814ad1a0e2981
This just copies over that update.
=> Update fetch-configlet scripts from exercism/configlet

.github/workflows/auto-rebase.yml
Additional details [here](https://github.com/cirrus-actions/rebase/commit/f72b20de85657401499fc29a910469d7663a78dc) and [here](https://bugs.chromium.org/p/project-zero/issues/detail?id=2070&can=2&q=&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Summary&cells=ids).
=> [CI] Bump rebase action to fix CVE-2020-15228

exercises/luhn/example.jl
This is a lot more readable, imo. It's more efficient, too, though we
can fairly easily go 25x faster than this one.
=> Improve example for luhn exercise

config.json
=> Deprecate transpose

.github/labels.yml, .github/workflows/sync-labels.yml
Use existing labels & copy JS label defs
---
Just some tooling to make it easier to update and change the labels and achieve some consistency across tracks
=> [CI] Add label sync

CODE_OF_CONDUCT.md
In preparation of non-English mentoring in v3.
=> Specify CoC for non-English languages

exercises/concept/annalyns-infiltration/.meta/config.json, exercises/concept/annalyns-infiltration2/.meta/config.json, exercises/concept/elyses-enchantments/.meta/config.json, exercises/concept/encounters/.meta/config.json, exercises/concept/fibonacci-iterator/.meta/config.json, exercises/concept/lasagna/.meta/config.json, exercises/concept/stage-heralding/.meta/config.json, exercises/concept/vehicle-purchase/.meta/config.json
Some exercises are still missing because it's not yet clear what their story will be or how they will fit in to the progression.
=> Add concept exercise blurbs

config.json, exercises/concept/annalyns-infiltration2/.docs/introduction.md
Annalyn's Infiltration Ⅱ is currently the first (and only?) exercise where several methods of a function (`rand`) are called
Encounters will remain the first method where such methods are implement by the student but they should already be aware that a function can have several methods.
=> Let annalyn2 unlock methods concept

config.json, exercises/concept/elyses-analytic-enchantments/.docs/hints.md, exercises/concept/elyses-analytic-enchantments/.docs/instructions.md, exercises/concept/elyses-analytic-enchantments/.docs/introduction.md, exercises/concept/elyses-analytic-enchantments/.meta/config.json, exercises/concept/elyses-analytic-enchantments/.meta/exemplar.jl, exercises/concept/elyses-analytic-enchantments/runtests.jl
The point of this exercise is to introduce several Base methods to analyse the contents of vectors, and to familiarise the notion of predicate functions to students.
=> Add exercise: elyses-analytic-enchantments / predicates

exercises/concept/elyses-analytic-enchantments/.docs/hints.md, exercises/concept/elyses-analytic-enchantments/.docs/instructions.md, exercises/concept/elyses-analytic-enchantments/.meta/exemplar.jl, exercises/concept/elyses-analytic-enchantments/runtests.jl, exercises/concept/elyses-enchantments/.docs/hints.md, exercises/concept/elyses-enchantments/.docs/instructions.md, exercises/concept/elyses-enchantments/.meta/exemplar.jl, exercises/concept/elyses-enchantments/runtests.jl
https://github.com/exercism/julia/pull/367#discussion_r607083966
fixes #368
=> Rename stack to deck in Elyse exercises

exercises/concept/annalyns-infiltration/.docs/instructions.md, exercises/concept/annalyns-infiltration2/.docs/instructions.md
The `## Tasks` heading should not be in `instructions.md` files.
=> Remove Tasks heading from `instructions.md`

exercises/practice/hello-world/hello-world.jl
Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46
=> 🤖 Simplify `hello-world` stub

CONTRIBUTING.md, bin/generate-runtests.sh, concepts/functions/about.md, exercises/concept/stage-heralding/.meta/design.md, exercises/concept/vehicle-purchase/.meta/design.md, exercises/practice/resistor-color-trio/.meta/example.jl, exercises/practice/spiral-matrix/.meta/example.jl, reference/concepts.csv
Just a few random typo fixes, found automatically by my IDE.
=> Fix a few random typos

exercises/concept/documented-lasagna/.docs/hint.md, exercises/concept/documented-lasagna/.docs/instructions.md
It's basically just a repetition of the introduction, but hints are required and what else can you write there? 🤷‍♀️
=> Add hints to documented-lasagna

exercises/concept/lasagna/.docs/hints.md, exercises/concept/lasagna/.docs/introduction.md
I solved the lasagna exercise for the first time and noticed that the hints don't show up because of the wrong formatting of the file. I also went ahead and added some more obvious hints.
=> Concept exercise review: lasagna

concepts/arithmetic-operators/.meta/config.json, concepts/boolean-expressions/.meta/config.json, concepts/conditionals/.meta/config.json, concepts/if-expressions/.meta/config.json, concepts/short-circuit-evaluation/.meta/config.json, concepts/ternary-operator/.meta/config.json
=> Add missing .meta/config.json files for concepts

exercises/shared/.docs/debug.md
Based on @angelikatyborska's/Elixir's debug.md: https://github.com/exercism/elixir/blob/main/exercises/shared/.docs/debug.md
See also https://github.com/exercism/julia/pull/435
=> Add debug.md

exercises/concept/vehicle-purchase/.docs/instructions.md
`help you help you` has been changed to `help you`
=> Remove redundant wording from instructions.md

.github/workflows/auto-rebase.yml, .github/workflows/configlet.yml
=> Update actions/checkout & use hash

config.json, exercises/practice/killer-sudoku-helper/.docs/instructions.md, exercises/practice/killer-sudoku-helper/.meta/config.json, exercises/practice/killer-sudoku-helper/.meta/example.jl, exercises/practice/killer-sudoku-helper/runtests.jl
The following screenshots will be added to the examples once I figure out how to add images to exercises properly.
<details><summary>Example 1</summary>
</details>
<details><summary>Example 2</summary>
</details>
<details><summary>Example 3</summary>
</details>
=> Add practice exercise: killer-sudoku-helper

exercises/practice/matching-brackets/.meta/tests.toml, exercises/practice/matching-brackets/runtests.jl, exercises/practice/pangram/.meta/tests.toml, exercises/practice/prime-factors/.docs/instructions.md, exercises/practice/prime-factors/.meta/tests.toml, exercises/practice/prime-factors/runtests.jl, exercises/practice/rational-numbers/.docs/instructions.md, exercises/practice/rational-numbers/.meta/tests.toml, exercises/practice/rational-numbers/runtests.jl, exercises/practice/roman-numerals/.docs/instructions.md, exercises/practice/roman-numerals/.meta/tests.toml, exercises/practice/roman-numerals/runtests.jl
More will come but for now I'm done syncing, so this is ready for review & merging
=> Update some exercises to latest spec

exercises/practice/binary-search/.docs/instructions.md
fixing issue https://github.com/exercism/julia/issues/479#issue-1106059551
=> issue #479 adding julia docs examples

.github/CODEOWNERS
I don't have any interest in the dependabot and sync-org-wide-files PRs and I don't think Sascha does either.
Maintainers, please merge this if Sascha says they agree.
=> Don't botspam `@exercism/julia`

exercises/concept/leap/.approaches/config.json, exercises/concept/leap/.approaches/introduction.md, exercises/practice/atbash-cipher/.approaches/config.json, exercises/practice/atbash-cipher/.approaches/introduction.md, exercises/practice/bob/.approaches/config.json, exercises/practice/bob/.approaches/introduction.md, exercises/practice/clock/.approaches/config.json, exercises/practice/clock/.approaches/introduction.md, exercises/practice/difference-of-squares/.approaches/config.json, exercises/practice/difference-of-squares/.approaches/introduction.md, exercises/practice/hamming/.approaches/config.json, exercises/practice/hamming/.approaches/introduction.md, exercises/practice/leap/.approaches, exercises/practice/luhn/.approaches/config.json, exercises/practice/luhn/.approaches/introduction.md, exercises/practice/nucleotide-count/.approaches/config.json, exercises/practice/nucleotide-count/.approaches/introduction.md, exercises/practice/pangram/.approaches/config.json, exercises/practice/pangram/.approaches/introduction.md, exercises/practice/phone-number/.approaches/config.json, exercises/practice/phone-number/.approaches/introduction.md, exercises/practice/pythagorean-triplet/.approaches/config.json, exercises/practice/pythagorean-triplet/.approaches/introduction.md, exercises/practice/robot-name/.approaches/config.json, exercises/practice/robot-name/.approaches/introduction.md, exercises/practice/rotational-cipher/.approaches/config.json, exercises/practice/rotational-cipher/.approaches/introduction.md
Copy (and lightly edit) our mentoring notes from exercism/website-copy so that they're visible in the new "Dig Deeper" tab (also known as "Approaches").
This PR copies 13/18 mentoring notes adapted to the new format. More PRs may follow for the other mentoring notes.
Configlet will cry about this PR, but this should be force merged anyway.
=> Dig deeper

exercises/concept.wip/leap/.approaches/introduction.md, exercises/practice/atbash-cipher/.approaches/introduction.md, exercises/practice/bob/.approaches/introduction.md, exercises/practice/clock/.approaches/introduction.md, exercises/practice/difference-of-squares/.approaches/introduction.md, exercises/practice/hamming/.approaches/introduction.md, exercises/practice/luhn/.approaches/introduction.md, exercises/practice/nucleotide-count/.approaches/introduction.md, exercises/practice/pangram/.approaches/introduction.md, exercises/practice/phone-number/.approaches/introduction.md, exercises/practice/pythagorean-triplet/.approaches/introduction.md, exercises/practice/robot-name/.approaches/introduction.md, exercises/practice/rotational-cipher/.approaches/introduction.md
- approaches: use consistent general guidance headings
- approaches: use consistent "## Approach: " prefix
This is to prepare for extracting the approaches to individual approach documents.
=> Approaches: tweaks

concepts.wip/arithmetic-operators/.meta/config.json, concepts.wip/arithmetic-operators/introduction.md, concepts.wip/arithmetic-operators/links.json
- blurb for arithmetic-operators,
- links for arithmetic-operators,
- introduction for arithmetic-operators.
=> Arithmetic operators update

concepts.wip/arithmetic-operators/.meta/config.json, concepts.wip/arithmetic-operators/about.md, concepts.wip/arithmetic-operators/introduction.md, concepts.wip/arithmetic-operators/links.json
- Added detailed content for about page related to arithmetic operators in Julia.
Looking forward to your review and suggestions.
Thanks.
=> Arithmetic operators update for about page

concepts.wip/boolean-expressions/.meta/config.json, concepts.wip/boolean-expressions/about.md, concepts.wip/boolean-expressions/introduction.md, concepts.wip/boolean-expressions/links.json
- Add blurb to `config.json`,
- Add links to `links.json`,
- Add intro page,
- Add about page.
***Please let me know if the about page is correct and sufficient.***
Thanks in advance!
=> Boolean expression update

concepts.wip/boolean-logic/.meta/config.json, concepts.wip/boolean-logic/about.md, concepts.wip/boolean-logic/introduction.md, concepts.wip/boolean-logic/links.json
- Add blurb to `config.json`
- Add about to `about.md`
- Add introduction to `introduction.md`
- Add links to `links.json`
=> Boolean logic update

concepts.wip/booleans/.meta/config.json, concepts.wip/booleans/about.md, concepts.wip/booleans/introduction.md, concepts.wip/booleans/links.json
- Add extra info and sentence restructuring to `about.md`
- Add links to `links.json`
- Add extra info to `introduction.md`
- Add to `config.json`
=> Booleans update

exercises/practice/binary-search/.docs/instructions.append.md, exercises/practice/binary-search/.docs/instructions.md, exercises/practice/binary-search/.docs/introduction.md
The binary-search exercise has been overhauled as part of a project to make practice exercises more consistent and friendly.
For more context, please see the discussion in the forum, as well as the pull request that updated the exercise in the problem-specifications repository:
- https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943
- https://github.com/exercism/problem-specifications/pull/2220
=> Sync binary-search docs with problem-specifications

exercises/practice/sum-of-multiples/.docs/instructions.append.md, exercises/practice/sum-of-multiples/.docs/instructions.md
Also removed .append as I don't think we need it any more.
=> sync sum-of-multiples instructions

exercises/practice/sum-of-multiples/.approaches/introduction.md
I misleadingly claimed that `prod(itr)` gives the right answer if its result is >= 0, but that's just complete nonsense.
=> Improve sum-of-multiples approaches intro

exercises/practice/largest-series-product/.docs/instructions.md
https://github.com/exercism/problem-specifications/pull/2234
=> Sync largest series product description

exercises/practice/largest-series-product/.approaches/introduction.md
Some minor changes to the approaches file.
=> Largest series improvements

exercises/practice/sum-of-multiples/.approaches/introduction.md
I'm not sure whether this should be included (or if it should be included, whether it should be included here), but I wrote the code for it while I was testing different approaches for the exercise, so I thought I might as well write it up.
=> Explain how to automatically pick between a BitSet and a Set{Int}

exercises/concept.wip/annalyns-infiltration/.docs/instructions.md
Responding to @ErikSchierboom comments in #569. Is it better than the original?
=> [annalyns-infiltration]: edited instructions.md for #569

exercises/concept.wip/documented-lasagna/.docs/hints.md, exercises/concept.wip/documented-lasagna/.docs/instructions.md
resolves #578 
- Split instructions from 1 task into 3
- Added a little bit more lore
- Put all hints in general
=> [documented-lasagna]: Updated instructions.

concepts.wip/boolean-logic/introduction.md, concepts.wip/booleans/introduction.md, exercises/concept.wip/annalyns-infiltration/.docs/instructions.md, exercises/concept.wip/annalyns-infiltration/.docs/introduction.md
An attempt to address #570, criticism welcome.
Based on `concept.wip/booleans` and `boolean-logic`, but significantly simplified for an early concept exercise. It may still be too long?
=> [annalyns-infiltration] added introduction.md

exercises/practice/sum-of-multiples/.docs/instructions.md
This adds some follow-on tweaks to the sum-of-multiples documentation, after the recent overhaul in problem-specifications.
=> Sync tweaks to sum-of-multiples

exercises/practice/pythagorean-triplet/.docs/instructions.md, exercises/practice/pythagorean-triplet/.docs/introduction.md, exercises/practice/pythagorean-triplet/pythagorean-triplet.jl
=> Improve instructions, story and stub for pythagorean-triplets

exercises/practice/word-count/.approaches/config.json, exercises/practice/word-count/.approaches/introduction.md
Original file:
https://github.com/exercism/website-copy/blob/main/tracks/julia/exercises/word-count/mentoring.md
I've revised the text and solutions a bit and removed one solution that works badly with the new instructions.
=> Convert word-count mentoring notes to approaches intro

exercises/practice/roman-numerals/.approaches/config.json, exercises/practice/roman-numerals/.approaches/introduction.md
Taken from the mentoring notes
=> Add roman-numerals approaches intro

exercises/practice/isbn-verifier/isbn-verifier.jl
=> Add stub file to isbn-verifier telling student to define a struct

exercises/practice/secret-handshake/.docs/instructions.md
=> Sync secret-handshake instructions

exercises/practice/anagram/runtests.jl, exercises/practice/collatz-conjecture/runtests.jl, exercises/practice/complex-numbers/runtests.jl, exercises/practice/darts/runtests.jl, exercises/practice/difference-of-squares/runtests.jl, exercises/practice/hamming/runtests.jl, exercises/practice/hello-world/runtests.jl, exercises/practice/isogram/runtests.jl, exercises/practice/killer-sudoku-helper/runtests.jl, exercises/practice/leap/runtests.jl, exercises/practice/nucleotide-count/runtests.jl, exercises/practice/pangram/runtests.jl, exercises/practice/pythagorean-triplet/runtests.jl, exercises/practice/raindrops/runtests.jl, exercises/practice/reverse-string/runtests.jl, exercises/practice/rna-transcription/runtests.jl, exercises/practice/rotational-cipher/runtests.jl, exercises/practice/saddle-points/runtests.jl, exercises/practice/scrabble-score/runtests.jl, exercises/practice/secret-handshake/runtests.jl
Verbose Unit Testing
- killer-sudoku-helper
- hamming
- saddle-points
- pangram (fix)
- leap
- pythagorean-triplet
- collatz-conjecture
- hello-world
- complex-numbers
- raindrops
- nucleotide-count
- rotational-cipher
- difference-of-squares
- secret-handshake
- darts
- rna-transcription
- scrabble-score
- reverse-string
- isogram
- anagram
Type Specification
> Specify the input type to align the output type for easier unit testing.
- saddle-points
=> Verbose Unit Testing for Comprehensive Testing Part 1/3

config.json, exercises/practice/space-age/.docs/instructions.md, exercises/practice/space-age/.meta/config.json, exercises/practice/space-age/.meta/example.jl, exercises/practice/space-age/.meta/tests.toml, exercises/practice/space-age/runtests.jl, exercises/practice/space-age/space-age.jl
@exercism/julia, part of #48in24.
=> Add space-age exercise

config.json, exercises/practice/resistor-color/.docs/instructions.md, exercises/practice/resistor-color/.meta/config.json, exercises/practice/resistor-color/.meta/example.jl, exercises/practice/resistor-color/.meta/tests.toml, exercises/practice/resistor-color/resistor-color.jl, exercises/practice/resistor-color/runtests.jl
=> Add resistor-color exercise

exercises/practice/raindrops/.docs/instructions.md, exercises/practice/raindrops/.docs/introduction.md, exercises/practice/raindrops/.meta/config.json
Sync the `raindrops` exercise with the latest data, as defined in https://github.com/exercism/problem-specifications/tree/main/exercises/raindrops.
- Feel free to close this PR if there is another PR that also syncs this exercise.
- When approved, feel free to merge this PR yourselves (you don't have to wait for me).
As this PR only updates docs and/or metadata, it won't trigger a re-run of existing solutions (see [the docs](https://exercism.org/docs/building/tracks)).
=> raindrops: sync

config.json, exercises/practice/two-fer/.docs/instructions.md, exercises/practice/two-fer/.docs/introduction.md, exercises/practice/two-fer/.meta/config.json, exercises/practice/two-fer/.meta/example.jl, exercises/practice/two-fer/.meta/tests.toml, exercises/practice/two-fer/runtests.jl, exercises/practice/two-fer/two-fer.jl
=> Add two-fer exercise

.github/workflows/exercise-tests.yml
I'm testing if this fixes the macOS build.
=> Upgrade julia version

config.json, exercises/practice/protein-translation/.docs/instructions.md, exercises/practice/protein-translation/.meta/config.json, exercises/practice/protein-translation/.meta/example.jl, exercises/practice/protein-translation/.meta/tests.toml, exercises/practice/protein-translation/protein-translation.jl, exercises/practice/protein-translation/runtests.jl
=> Add protein-translation

config.json, exercises/practice/two-bucket/.docs/instructions.md, exercises/practice/two-bucket/.meta/config.json, exercises/practice/two-bucket/.meta/example.jl, exercises/practice/two-bucket/.meta/tests.toml, exercises/practice/two-bucket/runtests.jl, exercises/practice/two-bucket/two-bucket.jl
I've submitted the exercise with the tests from `canonical-data.json` and a more mathematical `example.jl`.
- I've marked this as a 4 difficulty, but could see it also as a 3.
- Testing in `canonical-data.json` could be augmented with further edge cases.
Below are some extra edge cases which I encountered while working on the more mathematical  implementation, but I only included a few here. I was testing against a more procedural implementation, which can be found below the tests (the two algorithms are mutually consistent as far as I can tell). 
Lastly, below that, there is a function to produce example input, which I used to test the two implementations against each other.
Extra edge cases which could be added to testing:
```julia
@testset "Buckets are same size but goal is different" …
```
=> add new practice exercise two bucket

config.json, exercises/practice/diamond/.docs/instructions.md, exercises/practice/diamond/.meta/config.json, exercises/practice/diamond/.meta/example.jl, exercises/practice/diamond/.meta/tests.toml, exercises/practice/diamond/diamond.jl, exercises/practice/diamond/runtests.jl
Other tracks disagree wildly about difficulty, from Python: 2 to C#: 8 and everything in between. I went with 3.
=> add practice exercise Diamond

config.json, exercises/practice/kindergarten-garden/.docs/instructions.md, exercises/practice/kindergarten-garden/.docs/introduction.md, exercises/practice/kindergarten-garden/.meta/config.json, exercises/practice/kindergarten-garden/.meta/example.jl, exercises/practice/kindergarten-garden/.meta/tests.toml, exercises/practice/kindergarten-garden/kindergarten-garden.jl, exercises/practice/kindergarten-garden/runtests.jl
Difficulty 3 copies Python and C#
=> add practice exercise kindergarten-garden

config.json, exercises/practice/grade-school/.docs/instructions.md, exercises/practice/grade-school/.meta/config.json, exercises/practice/grade-school/.meta/example.jl, exercises/practice/grade-school/.meta/tests.toml, exercises/practice/grade-school/grade-school.jl, exercises/practice/grade-school/runtests.jl
Difficulty 3 copies Python and C#. Other tracks give it a higher difficulty, and increasing to 4 might be reasonable?
=> add practice exercise grade-school

bin/add-practice-exercise, bin/fetch-configlet.ps1, bin/verify-exercises, bin/verify-exercises-in-docker
As discussed in #783. These files are supplied to new tracks by default, this is an older track catching up.
=> Standard scripts copied from generic-track repo

config.json, exercises/concept/high-school-sweetheart/.docs/hints.md, exercises/concept/high-school-sweetheart/.docs/instructions.md, exercises/concept/high-school-sweetheart/.docs/introduction.md, exercises/concept/high-school-sweetheart/.meta/config.json, exercises/concept/high-school-sweetheart/.meta/design.md, exercises/concept/high-school-sweetheart/.meta/exemplar.jl, exercises/concept/high-school-sweetheart/high-school-sweetheart.jl, exercises/concept/high-school-sweetheart/runtests.jl
Reboot of PR(https://github.com/exercism/julia/pull/830)
=> add high-school-sweetheart concept exercise

concepts.wip/array-operations/.meta/config.json, concepts.wip/array-operations/about.md, concepts.wip/array-operations/introduction.md, concepts.wip/array-operations/links.json
A few days ago, there was some discussion about when/how to explain broadcasting. This is one attempt to answer that question.
I suspect there are gaps (especially in talking about useful Julia functions). I'll add more content once I translate that vague feeling into something more specific.
=> Vector Operations

config.json, exercises/concept/bird-watcher/.docs/hints.md, exercises/concept/bird-watcher/.docs/instructions.md, exercises/concept/bird-watcher/.docs/introduction.md, exercises/concept/bird-watcher/.meta/config.json, exercises/concept/bird-watcher/.meta/design.md, exercises/concept/bird-watcher/.meta/exemplar.jl, exercises/concept/bird-watcher/bird-watcher.jl, exercises/concept/bird-watcher/runtests.jl
The first 5 tasks are borrowed from C#, I just made up the 6th to give more practice with arithmetic. would you like additions or changes?
=> `bird-watcher` concept exercise

config.json
shortest PR I've ever submitted
=> untangle lasagna concepts in config.json

concepts/vector-operations/.meta/config.json, concepts/vector-operations/about.md, concepts/vector-operations/introduction.md, concepts/vector-operations/links.json, config.json
After an unfortunate merge mishap with #819, this PR attempts to remedy the situation.
=> Vector operations (rescue attempt)

concepts/strings/.meta/config.json, concepts/strings/about.md, concepts/strings/introduction.md, concepts/strings/links.json, config.json
Finally, something to PR (I started this several months ago).
This is a big concept, and many other parts of the syllabus have it as a prereq. Please look at it with a skeptical eye, and feel uninhibited in making criticisms.
I'll aim to get `log-levels` submitted later today, to go with this. I'll probably try to update `chars` (#805) and `squeaky-clean` (#806) over the weekend, because strings and chars are so closely related. Also, I find this part of the syllabus more of a slog to write than the mathematical stuff, so I'd like to get it finished then move on.
=> Strings concept

concepts/chars/.meta/config.json, concepts/chars/about.md, concepts/chars/introduction.md, concepts/chars/links.json, config.json
=> chars concept, another attempt

exercises/concept/bird-watcher/.docs/instructions.md, exercises/concept/cater-waiter/.meta/config.json, exercises/concept/currency-exchange/.docs/instructions.md, exercises/concept/currency-exchange/.meta/config.json, exercises/concept/elyses-enchantments/.docs/instructions.md, exercises/concept/high-school-sweetheart/.meta/config.json, exercises/concept/log-levels/.docs/instructions.md, exercises/concept/squeaky-clean/.docs/instructions.md
Addresses comments made in #848, plus a few errors I found during the read-through.
I also ran `configlet fmt -u -y` to get rid of some warning messages.
=> Fix various formatting glitches

exercises/concept/cater-waiter/.docs/instructions.md, exercises/concept/cater-waiter/.docs/introduction.md
Deleted some white space which made formatting awkward on the website.
=> Cater waiter update

concepts.wip/config.json
This is step 1. We can set status to deprecated in a later step (assuming this goes through without breaking anything).
=> emptied concepts and prerequisites fields

concepts.wip/config.json
set everything to "status": "deprecated". Also cleaned up Lasagna, which I missed earlier.
=> Deprecate concept exercises

concepts.wip/config.json, config.json
Swapping the UUIDs between duplicate the duplicate exercise `annalyns-infiltration` and the concept `conditionals`
=> Swap uuids

concepts.wip/config.json, config.json
=> Revert "Swap uuids"

config.json, exercises/concept/old-elyses-enchantments/.docs/hints.md, exercises/concept/old-elyses-enchantments/.docs/instructions.md, exercises/concept/old-elyses-enchantments/.docs/introduction.md, exercises/concept/old-elyses-enchantments/.meta/config.json, exercises/concept/old-elyses-enchantments/.meta/exemplar.jl, exercises/concept/old-elyses-enchantments/enchantments.jl, exercises/concept/old-elyses-enchantments/runtests.jl
Submitting this with some trepidation. I _think_ it repeats what worked for Annalyn...
=> Deprecating old-elyses-enchantments

exercises/practice/fft/.docs/hints.md
Changing the `hints.md` format, to align with practice exercise format.
=> change hints.md format

config.json, exercises/concept/grading-guru/.docs/design.md, exercises/concept/grading-guru/.docs/hints.md, exercises/concept/grading-guru/.docs/instructions.md, exercises/concept/grading-guru/.docs/introduction.md, exercises/concept/grading-guru/.meta/config.json, exercises/concept/grading-guru/.meta/exemplar.jl, exercises/concept/grading-guru/grading-guru.jl, exercises/concept/grading-guru/runtests.jl
This is a rough draft of a concept exercise meant to pair with [`Types`](https://github.com/exercism/julia/pull/921). I'm open to any suggestions as I'm not sure how much more functionality we should try to fit in or if the story is sufficiently reasonable.
Some notes:
- An attempt to use both concrete and abstract comparisons.
- Type conversion is necessary, but promotion is not.
- At a minimum, the set of { `isa`, `==`, `typeof`, `Int8`, `UInt8`} are `Type` related functions necessary to complete the exercise.
- Function stories are a bit contrived, but I was trying to avoid solutions which work with both valid data types (e.g. easy to sort both a vector and a set with the same code => `sort!(collect(vector/set))`)
- Since error handling concept hasn't been broached, a string mimicking …
=> Grading guru

config.json, exercises/concept/role-playing-game/.docs/hints.md, exercises/concept/role-playing-game/.docs/instructions.md, exercises/concept/role-playing-game/.docs/introduction.md, exercises/concept/role-playing-game/.meta/config.json, exercises/concept/role-playing-game/.meta/design.md, exercises/concept/role-playing-game/.meta/exemplar.jl, exercises/concept/role-playing-game/role-playing-game.jl, exercises/concept/role-playing-game/runtests.jl
This is a first go at the Role Playing Game adapted for Julia. I think this give some good practice with composite types, as well as about as much as we can hope for with type unions. Some notes:
- There are seven tasks, but I've tried to keep them fairly simple. Most can be solved with a ternary operator.
- Task 7 is currently unnecessary for in regards to the aims for the concept. It was left in to add more context, but could be removed
- I used the `name` and `mana` as arguments for the `increment` methods to give another chance to use the type union definitions from Task 1.
- The annotations of all the functions have been deleted, so students can be encouraged to do that themselves (for the `increment` methods at a minimum).
- The `name` method for `increment` feels a bit contrived, …
=> add concept exercise role-playing-game

exercises/concept/role-playing-game/.meta/config.json, exercises/concept/role-playing-game/.meta/exemplar.jl, exercises/concept/role-playing-game/runtests.jl
- Added the tests for the output of the function `title`. 
- Included @colinleach as an author
- Refined `exemplar.jl` to incorporate all parts of the final exercise
=> add tests for output, plus other nits

exercises/concept/tisbury-treasure-hunt/.docs/instructions.md
Corrects function calls in examples that demonstrate the expected function behavior.
=> Adds brackets to examples in section 3 and 4
