exercism/julia

README.md

As discussed in issue #2.
Closes #2

Added exercise structure to README

---

docs/INSTALLATION.md

This PR adds some basic instructions on how to find installation instructions for Julia. They're mostly based on the info provided on the [Julia Language website](http://julialang.org/downloads/).
I've also added two common issues I've encountered when helping others install Julia. Given the amount of Google results regarding the first question, I thought it might be a good idea to mention it and provide a starting point on how to resolve them. If that's not wanted, I will remove it.
---
PS: It's nice to see Julia on exercism.io, it's quite hard to find easily available challenges specifically for Julia at the moment. :)

Documentation: Installation instructions

---

.travis.yml
README.md
docs/TESTS.md
runtests.jl

This implements a test suite that can be used to run tests locally and on Travis CI. You can specify the example solutions to be tested via command line arguments. The default behaviour is to test all example solutions.
I've tested it both locally and on Travis CI for Julia v0.5 and the latest v0.6-dev build. It seemed to work but please check if I made any mistakes in `.travis.yml` as I don't have much experience with Travis.
(ref. #3)

CI Test suite (Fixes #3)

---

config.json
runtests.jl

Currently if one of the tests fails, the temporary directory is not deleted. This should fix this issue.

RFC: Fix removal of temp dir if tests fail

---

README.md

Add an example exercise entry for config.json in the README to make it easier for new contributors to find info in one place.

Additional info for adding exercises in README

---

config.json

Our test files are called `runtests.jl` and thus have `test` in the name, so this can be removed. (See #1)

Remove test_pattern config-key

---

.travis.yml

* osx builds take ~1h to start, causing issues for other tracks.
* disable the 0.5 build because release covers that as of the time of the PR

Disable osx travis builds & duplicate 0.5 build

---

.travis.yml

v0.5.1 has been released. While it should be compatible with v0.5, we should still test v0.5 to be sure as it will likely take some time for people to update.

Add v0.5.0 to travis testing

---

exercises/difference-of-squares/difference-of-squares.jl

Someone mentioned in a comment that the stub is in a different order than the description. This fixes it.
Trivial change so I'll merge it as soon as tests pass.

Difference of squares: Change order to fit readme

---

exercises/rotational-cipher/runtests.jl
runtests.jl

This finally fixes #45.
Now `@test_skip` and `@test_broken` will be overwritten with `@test` when running the tests via `runtests.jl` in the main directory. *This does not affect the person solving the exercise.*
~This only works on v0.6, so won't merge it before v0.6 launches (just like #58).~ Seems to work on v0.5 too, so if nobody has complaints, I will merge it next monday.

Optional/Skipped tests will be unskipped on Travis and Development

---

runtests.jl

Testsets now print the result by default again (this wasn't the case on earlier v0.6-dev versions) so we don't need the special case anymore.

Fix runtests: testset results print by default

---

exercises/custom-set/example.jl
exercises/luhn/example.jl

Do not merge before v0.6 is released!
---
This updates `custom-set` and `luhn` to v0.6. Currently all other exercises work just fine; the testsuites did not require updating.
---
This fixes #37.

Prepare exercises for v0.6

---

config/exercise_readme.go.tmpl
exercises/anagram/README.md
exercises/atbash-cipher/README.md
exercises/bob/README.md
exercises/complex-numbers/README.md
exercises/custom-set/README.md
exercises/difference-of-squares/README.md
exercises/etl/README.md
exercises/gigasecond/README.md
exercises/hamming/README.md
exercises/hello-world/README.md
exercises/isogram/README.md
exercises/leap/README.md
exercises/luhn/README.md
exercises/nucleotide-count/README.md
exercises/pangram/README.md
exercises/pascals-triangle/README.md
exercises/raindrops/README.md
exercises/rna-transcription/README.md
exercises/robot-name/README.md
exercises/roman-numerals/README.md
exercises/rotational-cipher/README.md
exercises/scrabble-score/README.md
exercises/secret-handshake/README.md
exercises/sieve/README.md
exercises/transpose/README.md
exercises/trinary/README.md
exercises/word-count/README.md

We are working towards making exercises stand-alone. That is to say: no more generating READMEs on the fly.
This will give maintainers more control over each individual exercise README, and it will also make some of the backend logic for delivering exercises simpler.
The README template uses the Go text/template package, and the default templates generate the same READMEs as we have been generating on the fly.  See the documentation in [regenerating exercise readmes][regenerate-docs] for details.
The READMEs can be generated at any time using a new 'generate' command in configlet. This command has not yet landed in master or been released, but can be built from source in the generate-readmes branch on [configlet][].
[configlet]: https://github.com/exercism/configlet
[regenerate-docs]: …

Generate static exercise README templates

---

config.json

See https://github.com/exercism/discussions/issues/175.
First attempt at a progression order through the track. Looks like this:

Add progression through exercises

---

config.json
exercises/phone-number/README.md
exercises/phone-number/example.jl
exercises/phone-number/phone-number.jl
exercises/phone-number/runtests.jl

This is a call-to-arm to issue #87. First time here, pardon me if anything is out of spec. Feel free to inform me on how I can polish it and I will get it fixed.
Some design decisions...
- The main machinery of this question is regex. Instead of mixing up regex with language specifics like some other language tracks, I decided to put the full power on regex. Instead the example demonstrates how Julia can call regex, and create regex using interpolation to improve code readability.
- I did not put in type declaration for the input variable, pending discussion on issue #2. I will adhere to the convention of this repo after we concluded the discussion.

Add exercise: phone-number

---

README.md

GitHub redirects, so it's not a critical fix.

Fix reference to renamed repo in README

---

config.json
exercises/isbn-verifier/README.md
exercises/isbn-verifier/example.jl
exercises/isbn-verifier/runtests.jl

I have extended the common problem specification to work with a custom string type and literal. This introduces new concepts and it behaves similar to version strings or LaTeXStrings.

Add exercise: isbn-verifier

---

exercises/nucleotide-count/example.jl
exercises/nucleotide-count/runtests.jl

In [my first cut of a solution](http://exercism.io/submissions/8ee2cc5ec49a464ba3d553c5a46a78ff) to this problem, I complained in a comment about the fact that the tests expect specifically an ErrorException, when a more specific error (KeyError) would be thrown otherwise.
Then @SaschaMann offered that maybe a DomainError is more appropriate, if we have to specify the type of the exception being thrown. I like that idea, so here is a PR that makes the change. I'm open to further discussion if anyone has thoughts on this.

Nucleotide Count: expect DomainError instead of ErrorException

---

config.json

While linting with the next release of [Configlet](https://github.com/exercism/configlet/releases/tag/v3.8.0) a number of exercises were still found to contain invalid unlocked_by configurations.
The master config file was updated following manner:
1. The exercise 'etl' is now unlocked_by the core exercise 'nucleotide-count', which is the core exercise that unlocks 'scrabble-score'.
1. The exercise 'isbn-verifier' is now unlocked_by the core exercise 'raindrops', which is the core exercise that unlocks 'luhn'.
1. Download the pre-release of Configlet [here](https://github.com/exercism/configlet/releases/tag/v3.8.0)
1. Run `configlet lint <path-to-fsharp-track>`
1. Validate that there are no lint errors.
closes #107

config.json: Update exercise ordering

---

config.json

Some of the topics used in `config.json` had the same meaning as topics in `problem-specification/TOPICS.txt` but had slightly different names. This PR updates them to follow the conventional names wherever possible.

 Change exercise topics to be more similar to shared TOPICS.txt 

---

.github/workflows/ci-workflow.yml

This runs the exercise tests as a GitHub action/workflow. The configlet, notebook checking etc. solely run on Travis for now.

Add basic GitHub actions CI for exercise tests

---

exercises/leap/leap.ipynb
exercises/leap/leap.jl
exercises/nucleotide-count/nucleotide-count.ipynb
exercises/nucleotide-count/nucleotide-count.jl
exercises/pangram/pangram.ipynb
exercises/pangram/pangram.jl

Users often overdo it on the type annotations in a way that is
unidiomatic for Julia and contrary to the recommendations of experienced
Julia programmers like Lyndon White and the Julia core team.
To provide some guidance to users, I've added docstrings to all of the
exercise skeletons that I've removed annotations from (the first three
in the track).

Use docstrings instead of type annotations

---

exercises/pangram/runtests.jl

I received one solution where it was only checked whether there are exactly 26 letters (case sensitive)
This would result in that `a...m A...M` is a pangram for example.
Also fails if there are more than 26 letters when counting i.e o and O as two different ones.

Fail if  there are 26 letters case sensitive

---

exercises/hamming/example.jl
exercises/hamming/hamming.ipynb
exercises/hamming/hamming.jl

Type annotations are baaad.
In this case, for common solutions, the code will work for any iterable,
but with type annotations it will be artificially restricted to strings.
That's not clever.
Updated example.jl slightly while I was here, because `count` is a bit
nicer than mapreduce.

Remove type annotations from hamming

---

bin/generate-notebooks.jl

This will break workflows that rely on generate-notebooks working for
other directories, but I think that's pretty unlikely.

Make generate-notebooks less fiddly to call

---

exercises/pythagorean-triplet/example.jl

This shaves 25% off the test time for me.

Faster tests with a fast pythagorean-triplet example

---

exercises/reverse-string/README.md
exercises/reverse-string/example.jl
exercises/reverse-string/reverse-string.jl
exercises/reverse-string/runtests.jl

Closes #238. I've put in a compulsory unicode test with an emoji and
left the grapheme tests optional for now because they're a bit fiddlier
to get right.

reverse-string: encourage grapheme awareness

---

.github/CODEOWNERS

This will automatically request a review from Julia maintainers.
Later rules in the CODEOWNERS file take precedence, so the maintainers.json and CODEOWNERS rules are unaffected: https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners#example-of-a-codeowners-file

Add Julia maintainers as default codeowners

---

.github/workflows/exercise-tests.yml

GitHub shows these in the UI anyway

CI: Remove redundant github.event_name

---

exercises/practice/nucleotide-count/nucleotide-count.jl

I got tricked by my own excitement beginning the julia track.
I started solving the Nucleotide Count exercise without a complete reading of its introduction;
the comment at the beginning seemed just enough:
> count_nucleotides(strand)
> The frequency of each nucleotide within `strand` as a dictionary.
> Invalid strands raise a `DomainError`.
So I read **frequency** and I think: count(nt) / length(strand) 
It was fun solving that.. Untill the tests revealed  my mistake:
we are asked to return the count of each nucleotide: not their frequencies.
To avoid the confusion -for future students- I'd propose to replace "frequency" with "count" in the comment of the exercise's .jl file.

Update nucleotide-count.jl comment

---

config.json
exercises/concept/stage-heralding/.meta/design.md

This is mostly nothing new but info from the review and exercise testing. Having it in the design.md file makes it easier to refer back to these decisions.

stage-heralding: Add design & remove no-longer-needed pre-req

---

exercises/concept/annalyns-infiltration/.meta/config.json
exercises/concept/annalyns-infiltration2/.meta/config.json
exercises/concept/elyses-enchantments/.meta/config.json
exercises/concept/emoji-times/.meta/config.json
exercises/concept/encounters/.meta/config.json
exercises/concept/exercism-matrix/.meta/config.json
exercises/concept/fibonacci-iterator/.meta/config.json
exercises/concept/lasagna/.meta/config.json
exercises/concept/leap/.meta/config.json
exercises/concept/stage-heralding/.meta/config.json
exercises/concept/vehicle-purchase/.meta/config.json

The authors and contributors of exercises are stored in an array of objects in the exercises' `.meta/config.json` files.
Each author/contributor used to have two properties: their GitHub username _and_ their Exercism username.
As we're only using the GitHub username, we're flattening the `authors` and `contributors` array to an array of strings representing the GitHub usernames.
We will update `configlet` to validate the new structure, so you might be seeing build failures once we've implemented this change. 
See https://github.com/exercism/docs/pull/90/files
We will automatically merge this PR immediately to be able to submit a different PR in which we'll add the authors/contributors for practice exercises.
https://github.com/exercism/v3-launch/issues/26

🤖 Flatten authors and contributors in .meta/config.json files

---

exercises/concept/elyses-enchantments/.meta/config.json
exercises/concept/fibonacci-iterator/.meta/config.json
exercises/concept/lasagna/.meta/config.json
exercises/concept/leap/.meta/config.json
exercises/concept/vehicle-purchase/.meta/config.json

I've tried to apply the same policy as in #354 where all reviews count as contribution or more.

Add missing contributors and authors to concept exercises

---

concepts/abstract-types/.meta/config.json
concepts/boolean-logic/.meta/config.json
concepts/booleans/.meta/config.json
concepts/composite-types/.meta/config.json
concepts/constants/.meta/config.json
concepts/docstrings/.meta/config.json
concepts/emoji-symbols/.meta/config.json
concepts/functions-introduction/.meta/config.json
concepts/matrices-concatenation/.meta/config.json
concepts/matrices-indices/.meta/config.json
concepts/matrices-introduction/.meta/config.json
concepts/matrices-iteration/.meta/config.json
concepts/matrices-mutation/.meta/config.json
concepts/methods/.meta/config.json
concepts/multiple-dispatch/.meta/config.json
concepts/symbols/.meta/config.json
concepts/unicode-identifiers/.meta/config.json
config.json

_TL;DR; Add authors/contributors to a new `concepts/<slug>/.meta/config.json` to Concepts in the same way you have for Concept Exercises._
---
To properly attribute authorship/contributorship for an individual concept, each concept will have its own `.meta/config.json` file with `authors` and `contributors` keys like those for concept and practice exercises. We're also moving the concept's blurb from the track's `config.json` to the `.meta/config.json` file, also similar to concept and practice exercises.
See https://github.com/exercism/docs/pull/96/files for the update to the specification.
This PR adds a `.meta/config.json` file for all concepts found in the track's `config.json` file containing:
- A `blurb` key, which value is copied from the `config.json` file and subsequently removed …

🤖 Add .meta/config.json file for concepts

---

exercises/practice/phone-number/.docs/instructions.md
exercises/practice/phone-number/.meta/config.json
exercises/practice/phone-number/.meta/example.jl
exercises/practice/phone-number/runtests.jl

The instruction don't contain information about the conditions that "_detect an invalid number_" test is testing. Either this should be included, or the test should be removed (pr #373).
Note: Those first pull request ever... I have no idea what I'm doing. Please assume good will, if I'm doing it wrong.

phone-number: Update instructions to match tests

---

config.json

While I liked making them all exactly 100 chars long, I find it painful to look at some of the phrases and inconsistencies on the website.
The oxford comma is sometimes omitted due to the 100 char requirement.
---
You can see what it currently looks like on https://exercism.lol/tracks/julia (in incognito or logged out)

Slightly improve phrasing of key features

---

concepts/docstrings/.meta/config.json
concepts/docstrings/about.md

I didn't add it to the `instructions.md` of the concept exercise because it's not necessary to know why docstrings are useful in order to solve the exercise.

Clarify what a docstring is

---

.github/workflows/configlet.yml

New exercises should NOT introduce new configlet errors anymore, to prevent the number of errors from growing out of control before launch.
Making it annoying hopefully helps with that

Make configlet annoying again

---

exercises/shared/.docs/cli.md
exercises/shared/.docs/help.md
exercises/shared/.docs/tests.md

This resolves two of the linting problems.
As per https://github.com/exercism/docs/blob/main/building/tracks/shared-files.md, `help.md` and `tests.md` are necessary.
`cli.md` is not the responsibility of the track, it's a global file.
When I downloaded `bob` just now, this is the `HELP.md` file that was generated:
```markdown
You can submit your solution using the `exercism submit bob.jl` command.
This command will upload your solution to the Exercism website and print the solution page's URL.
It's possible to submit an incomplete solution which allows you to:
- See how others have completed the exercise
- Request help from a mentor
If you'd like help solving the exercise, check the following pages:
- The [Julia track's documentation](https://exercism.io/docs/tracks/julia)
- [Exercism's …
```

Add shared exercise docs

---

config.json

Track isn't in a state where it's likely to be launch-ready in time.

Disable concept exercises for testing

---

config.json

The `dictionaries` concept did not have any docs, which causes syncing to fail
Closes https://github.com/exercism/julia/issues/442

Remove dictionaries concept

---

exercises/practice/roman-numerals/runtests.jl

The testset name had a missing `()` around the string interpolation.

Minor testset fix in roman numerals tests

---

exercises/practice/robot-simulator/runtests.jl

As pointed out by PoliticalSatyr in their mentoring request, this isn't really needed.

robot-simulator: Remove type parameter from tests

---

exercises/practice/pangram/.docs/instructions.md

Contrary to what the current instructions say the tests do input non-ASCII characters, specifically test 14. 
In my personal opinion this only complicates the exercise without providing any sort of benefit to beginners, which are those most likely to attempt such an easy exercise.
Instead of removing the offending test I have decided to change the instructions instead, as I am unsure how to change the mentor notes, and the code solutions they contain.

Update instructions to reflect tests and mentor notes

---

exercises/practice/word-count/runtests.jl

I noticed this edge case (contractions with more than one letter after the apostrophe) while mentoring. Happy to use different/more examples or incorporate them into the original test if that is preferred

Add extra contraction test for word-count.jl

---

exercises/practice/alphametics/permutations.jl

defined in Combinatorics.jl and used in its `permutations`'s definition.
Solves this error:
```julia
julia> include("permutations.jl")
nextpermutation (generic function with 1 method)
julia> permutations([1,2,3]) |> collect
ERROR: MethodError: no method matching factorial(::Int64, ::Int64)
Closest candidates are:
factorial(::Union{Int64, UInt64}) at combinatorics.jl:27
factorial(::Integer) at intfuncs.jl:1007
Stacktrace:
[1] length
@ ~/exercism/julia/alphametics/permutations.jl:60 [inlined]
[2] _similar_shape
@ ./array.jl:663 [inlined]
[3] _collect
@ ./array.jl:718 [inlined]
[4] collect
@ ./array.jl:712 [inlined]
[5] |>(x::Permutations{Vector{Int64}}, f::typeof(collect))
@ Base ./operators.jl:911
[6] top-level scope
@ REPL[1]:1
```
With this fix:
```julia
julia> include("permutations.jl") …
```

Add missing `factorial` method

---

concepts/integer-introduction/about.md
concepts/integer-introduction/introduction.md
exercises/concept/lasagna/.docs/introduction.md

Turn every `~~~~note` into `~~~~exercism/note`.
Currently broken on e.g. https://exercism.org/tracks/julia/concepts/integer-introduction
From the [Exercism Markdown docs][1]:
> We support special types of blocks that can be added to documents to pull out commentary that doesn't fit with the main body of the text.
> 
> We support three types of blocks:
> 
> - **exercism/note:** Blocks that pull out some extra special information
> - **exercism/caution:** Things that people should know about or tread carefully with
> - **exercism/advanced:** Information that is only relevant for people who want to dig more deeply into something or are expected to have more advanced knowledge.
> 
> All blocks are written using 4 tildes, in the form of:
> 
> ````
> ~~~~exercism/note
> Content goes here
> 
> …
```

Fix broken admonitions

---

exercises/practice/pangram/runtests.jl

The instructions specify that the only input letters will be the 26 english language letters, but we were testing with unlauts.
I think it's worth changing the test rather than the instructions because it's ambiguous whether adding diacritics to a letter makes it a new letter or not.
I did think about adding a bonus test that makes a decision one way or the other (you could use unicode's NFKD transformation[1] to match letters, ignoring diacritics, or to require each unique glyph you could maybe use the NFC transformation + maybe splitting to graphemes (depending on if unicode has a codepoint for all "letters" in the alphabet)), but it's a bit complicated.
[1]: https://unicode.org/reports/tr15/

Fix #488 use non-ascii punctuation, not letters

---

exercises/practice/reverse-string/.docs/instructions.md

The bonus instruction appeared twice:
corrected by removing once of the occurences.

Reverse-string: remove repeated bonus instruction

---

exercises/practice/sum-of-multiples/runtests.jl

In `sum-of-multiples`, one of the tests pass an empty vector into the user's function. This is fine, but if the user adds types to their function arguments, you get an error:
```julia
function sum_of_multiples(limit::Int, factors::Vector{Int})::Int end
sum_of_multiples(20, [])
ERROR: MethodError: no method matching sum_of_multiples(::Int64, ::Vector{Any})
Closest candidates are:
sum_of_multiples(::Int64, ::Vector{Int64}) at REPL[1]:1
Stacktrace:
[1] top-level scope
```
This types the empty array in the test so that user functions will work whether or not they type them.

[sum-of-multiples] add a type to the empty vector in the test

---

exercises/practice/largest-series-product/.docs/instructions.md
exercises/practice/largest-series-product/.docs/introduction.md
exercises/practice/largest-series-product/.meta/tests.toml
exercises/practice/largest-series-product/runtests.jl

The largest-series-product exercise has been overhauled as part of a project to make practice exercises more consistent and friendly.
For more context, please see the discussion in the forum, as well as the pull request that updated the exercise in the problem-specifications repository:
- https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943
- https://github.com/exercism/problem-specifications/pull/2246 
Note that we have deprecated and removed two test cases that deal with the multiplicative identity (also referred to as an empty product). By doing this we were able to avoid talking about this at all, which makes this exercise much more approachable.
----
If you approve this pull request, I will eventually merge it. However, if …

Sync largest-series-product docs with problem-specifications

---

exercises/practice/rational-numbers/.docs/instructions.md
exercises/practice/rational-numbers/runtests.jl

These revisions make the rational numbers exercise easier by:
- introducing more tests (to guide the student to good solutions)
- making instructions more explicit
- removing tests that required correct handling of infinities (not specified in instructions)
- removing tests that required a custom `show` method (just not a good idea).
TODO: add an approach.
Closes #646

Make rational-numbers exercise easier

---

exercises/practice/resistor-color-trio/.approaches/config.json
exercises/practice/resistor-color-trio/.approaches/introduction.md
exercises/practice/resistor-color-trio/.docs/instructions.md
exercises/practice/resistor-color-trio/.meta/example.jl
exercises/practice/resistor-color-trio/runtests.jl

The tests we had were a bit bonkers. Possibly from a bad old version of problem-specifications, possibly our fault, whatever.
Now the tests and example are fine and the approaches intro is way too high effort.
The final `<details>` box might have been better being expanded out into separate approaches files, but I'd mostly written it by the time I decided that.
And it's kind of a pain having to rewrite it, generate UUIDs and JSON and excerpts, etc.
So I'm leaving it as is.

Fix resistor-color-trio and add approaches intro

---

exercises/practice/secret-handshake/.approaches/config.json
exercises/practice/secret-handshake/.approaches/introduction.md

Adapted from the mentoring notes in website-copy
ref #644

Add secret-handshake approaches

---

exercises/practice/atbash-cipher/.approaches/introduction.md
exercises/practice/gigasecond/.docs/introduction.md
exercises/practice/pangram/.docs/introduction.md
exercises/practice/rotational-cipher/.approaches/introduction.md

In line with Exercism's spec, we're ensuring that all admonition fences are demarcated with four tildes (`~~~~`) across all repositories. We will be following up with an org-wide script that can be used to keep this consistent. [Problem Specifications](https://github.com/exercism/problem-specifications) has already been updated.
We'll automatically merge this a week from now, but feel free to merge beforehand!
- Spec: https://exercism.org/docs/building/markdown/markdown#h-special-blocks-sometimes-called-admonitions
- Meta issue: https://github.com/exercism/exercism/issues/6705

Convert backtick (`) admonition fences to tildes (~)

---

.github/workflows/auto-rebase.yml
.github/workflows/exercise-tests.yml

This PR updates GitHub Actions runners to a specific version.
This ensures that the workflow will always run on the same runner, which makes your build _stable_.
The PR updates the *-latest version with the current version, as specified in https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-test-runners-to-version for more information.

CI: pin GitHub Actions runners

---

exercises/practice/pangram/runtests.jl

This pull request proposes enhancing the unit testing verbosity to provide a more comprehensive testing summary, which is particularly beneficial for CLI users. Here, I modified a single file to demo the result.
- Modified `exercises/practice/pangram/runtests.jl` to implement verbose unit testing.
- Nesting was introduced in unit tests to enhance readability and organization.
- Improved output format for better comprehension of test results.
It enhanced the readability and comprehensibility of testing output, especially for CLI users.
If this proposal is accepted, I plan to modify the other practices' unit testing further.

Use Verbose Unit Testing for Comprehensive Testing Summary

---

exercises/practice/roman-numerals/.meta/tests.toml
exercises/practice/roman-numerals/runtests.jl

I added the two tests that configlet noted as missing. The other changes to tests.toml seem to be the result of the existing tests being rearranged in ascending order for the number being tested.
[warn] roman-numerals: missing 2 test cases
- 3001 is MMMI (3bc4b41c-c2e6-49d9-9142-420691504336)
- 3999 is MMMCMXCIX (4e18e96b-5fbb-43df-a91b-9cb511fe0856)

Add new tests to roman numerals

---

runtests.jl

Reduce track-level runtests.jl output

---

exercises/practice/perfect-numbers/runtests.jl

Adds six tests which require the functions to return `false`, supplementing the previous testing whose inputs returned `true`, resolving [this issue](https://github.com/exercism/julia/issues/710)

Update tests in runtests.jl for perfect-numbers

---

.github/workflows/exercise-tests.yml

This reduces the odds of things accidentally breaking

Use explicit macos runner version

---

config.json
exercises/practice/dominoes/.docs/instructions.append.md
exercises/practice/dominoes/.docs/instructions.md
exercises/practice/dominoes/.meta/config.json
exercises/practice/dominoes/.meta/example.jl
exercises/practice/dominoes/.meta/tests.toml
exercises/practice/dominoes/dominoes.jl
exercises/practice/dominoes/runtests.jl

There are two suggestions for testing in the problem specifications. The more rigorous choice, of testing
a returned chain for validity, was used here in `runtests.jl` and requires a helper function to evaluate the users function. Main points: 
- Difficulty has been set at 5 due to a pruned dfs approach with returned chain
- Helper function needed for evaluation
Below is another implementation of the algorithm which simply returns true/false if a chain is possible.
The accompanying test set is below that. The change to the algorithm below is very minor, but this change may still be easier for some students. Due to this change being for less experienced students I have explicitly tested as `@test dominoes(input) == true/false` for clarity, instead of using the return value directly (i.e. …

add new practice exercise dominoes

---

config.json
exercises/practice/pig-latin/.docs/instructions.md
exercises/practice/pig-latin/.docs/introduction.md
exercises/practice/pig-latin/.meta/config.json
exercises/practice/pig-latin/.meta/example.jl
exercises/practice/pig-latin/.meta/tests.toml
exercises/practice/pig-latin/pig-latin.jl
exercises/practice/pig-latin/runtests.jl

Add pig-latin

---

config.json
exercises/practice/change/.docs/instructions.md
exercises/practice/change/.meta/config.json
exercises/practice/change/.meta/example.jl
exercises/practice/change/.meta/tests.toml
exercises/practice/change/change.jl
exercises/practice/change/runtests.jl

This is the practice exercise `change` from `problem-specifications`. The implementation is vanilla, and `example.jl` uses a fairly straightforward Dynamic Programming approach, so the only item that I feel of note is:
- Difficulty is set to 5 due to need for Dynamic Programming

add practice exercise change

---

config.json
exercises/practice/game-of-life/.docs/instructions.md
exercises/practice/game-of-life/.docs/introduction.md
exercises/practice/game-of-life/.meta/config.json
exercises/practice/game-of-life/.meta/example.jl
exercises/practice/game-of-life/.meta/tests.toml
exercises/practice/game-of-life/game-of-life.jl
exercises/practice/game-of-life/runtests.jl

Adding `game-of-life` from `problem-specifications`. This is a basic implementations with a straightforward matrix traversal `example.jl`. Only two things to note:
- Matrices used instead of nested vectors
- Difficulty set at 2, but I could imagine 3 due to use of matrices
For this exercise, the only salient differences between using nested vectors and matrices is likely just to be how the elements are accessed and/or how they are traversed.  I think this would be a gentle introduction to using matrices, if a user is new to them.

add practice exercise game-of-life

---

config.json
exercises/practice/wordy/.docs/instructions.md
exercises/practice/wordy/.meta/config.json
exercises/practice/wordy/.meta/example.jl
exercises/practice/wordy/.meta/tests.toml
exercises/practice/wordy/runtests.jl
exercises/practice/wordy/wordy.jl

Adding practice exercise `wordy` according to `problem-specifications`. A couple things to note:
- Difficulty set at 3, but 4 could be possible due to needing regex or otherwise having slightly complicated error handling.
That is all for the note for the implementation, but there is something I've found about being able to "hack" the error handling questions.
Below is an algorithm which doesn't use regex. Please note the line which is commented out:
```julia
ENG2MATH = zip(("plus","minus","divided by","multiplied by","What is ","?"), ("+","-","/","*","",""))
ops = Dict(zip(("+","-","/","*"), (+,-,/,*)))
function wordy(problem)
foreach(op -> problem = replace(problem, first(op) => last(op)), ENG2MATH)
terms = split(problem)
#iseven(length(terms)) && throw(ArgumentError(problem)) 
total, …
```

add practice exercise wordy

---

config.json
exercises/practice/palindrome-products/.docs/instructions.md
exercises/practice/palindrome-products/.meta/config.json
exercises/practice/palindrome-products/.meta/example.jl
exercises/practice/palindrome-products/.meta/tests.toml
exercises/practice/palindrome-products/palindrome-products.jl
exercises/practice/palindrome-products/runtests.jl

Adds practice exercise `palindrome-products` from `problem-specifications`. No changes have been made, and difficulty has been set at 4 due to the need for a non-brute-force algorithm. Let me know if there are any questions.

add practice exercise palindrome-products

---

config.json
exercises/practice/meetup/.docs/instructions.md
exercises/practice/meetup/.docs/introduction.md
exercises/practice/meetup/.meta/config.json
exercises/practice/meetup/.meta/example.jl
exercises/practice/meetup/.meta/tests.toml
exercises/practice/meetup/meetup.jl
exercises/practice/meetup/runtests.jl
generators/meetup.jl

A #48in24 exercise, highlighted in the week of August 20th.
Difficulty is provisionally set to 4, copying Python, C# and Crystal. I could easily be persuaded to drop to 3, copying Ruby.
The many tests are taking directly from `problem-specifications`. Unlike several other tracks, there are no additional tests of invalid input. Should these be added?
The file `generators/meetup.jl` created the tests adequately for present purposes, but is clunky. It's not clear to me that the track has agreed standards for these generator files?

add practice exercise meetup

---

config.json

The ordering of exercises on the [website page](https://exercism.org/tracks/julia/exercises) has become fairly random. It would be good to have them sorted easy-medium-hard like most other tracks.
I got a sorted list with jq:  `.exercises.practice | sort_by(.difficulty)`. There was some manual copying/pasting after that (I forgot a lot of jq, sorry!), but I was encouraged to see that I ended up with the same line count, and `configlet lint` was happy with the result. I think this gives us a list with difficulties 1-10, ascending. The Exercism website should follow this, perhaps after some delay.
Addressing the question of whether difficulties are correctly assigned is a whole other challenge.

Sort practice exercises by difficulty

---

.github/workflows/exercise-tests.yml

Some extracts from a recent Julia Language notification:
> The Julia developers are pleased to announce the release of Julia v1.11.0, the eleventh minor release in the 1.x series. 
> As a minor release, v1.11.0 contains no breaking changes, only new features, performance improvements, and marginal, non-disruptive changes in behavior. 
> We are also pleased to announce that Julia 1.10 is now the current long-term support (LTS) release, replacing 1.6. 
> With this, Julia 1.6 is now officially unmaintained. 
I propose to drop 1.6 testing, switching to 1.11, 1.10 and nightly. I ran the CI workflow on my branch: it completed successfully in under 3 minutes.
With 1.6, we had both MacOS compatibility issues and very slow (15-20 min) CI on Windows, so I will be very happy to remove it. …

update CI versions to Julia 1.11 (current) and 1.10 LTS

---

config.json
exercises/concept/lasagna/.docs/hints.md
exercises/concept/lasagna/.docs/instructions.md
exercises/concept/lasagna/.docs/introduction.md
exercises/concept/lasagna/.docs/introduction.md.tpl
exercises/concept/lasagna/.meta/config.json
exercises/concept/lasagna/.meta/design.md
exercises/concept/lasagna/.meta/exemplar.jl
exercises/concept/lasagna/lasagna.jl
exercises/concept/lasagna/runtests.jl
exercises/practice/resistor-color/.docs/instructions.md

For discussion on the [forum](https://forum.exercism.org/t/julia-learning-track-redux/12826/16)
This revision (the most recent of many):
- Rewrites and shortens the `introduction.md` to meet Exercism guidelines.
- Enforces use of a constant, in place of magic numbers within the code.
- Points the top-level `config.sys` to the `basics` concept, instead of 3 older ones.
The old documentation isn't wasted: I moved some to `basics/about.md` and some to later concepts.
Including the `introduction.md.tpl` was my mistake. It should probably be removed now we no longer need to combine bits from 3 concepts.

[Lasagna] revision to existing concept exercise

---

concepts.wip/function-composition/.meta/config.json
concepts.wip/function-composition/about.md
concepts.wip/function-composition/introduction.md
concepts.wip/function-composition/links.json

I haven't looked closely at exercises to match this, but other tracks seem to use `high-school-sweetheart`.

WIP draft of function-composition concept

---

config.json
exercises/concept/cater-waiter/.docs/hints.md
exercises/concept/cater-waiter/.docs/instructions.md
exercises/concept/cater-waiter/.docs/introduction.md
exercises/concept/cater-waiter/.meta/config.json
exercises/concept/cater-waiter/.meta/exemplar.jl
exercises/concept/cater-waiter/cater-waiter.jl
exercises/concept/cater-waiter/runtests.jl
exercises/concept/cater-waiter/sets_categories_data.jl

A second attempt at adding cater-waiter. Previous is [PR #818](https://github.com/exercism/julia/pull/818/files)
I haven't included `sets_test_data.jl` since I believe it was superfluous with the current setup putting everything in `exemplar.jl`, but we'll see if the checks pass.

add cater-waiter concept exercise

---

exercises/concept/cater-waiter/.docs/instructions.md
exercises/concept/cater-waiter/.docs/introduction.md

This corrects some inconsistencies in the REPL formatting for the `cater-waiter` exercise, plus a few extraneous whitespaces.

Cater waiter reformat

---

concepts.wip/config.json

These UUIDs have already been reused at the top level. Removing them is a small step towards simplification.

Remove defunct entries from concepts.wip/config.json

---

exercises/concept/captains-log/.docs/instructions.md
exercises/concept/captains-log/.meta/exemplar.jl

Both changes are related to Task 3 of the Captain's Log exercise.
**1) Change to** `instructions.md`
In `instructions.md`, Task 3 states that the generator should produce "_a floating point number between 41000.0 and 42000.0 (inclusive)_". However, `rand()` returns a value from a continuous uniform distribution over the open interval (0, 1). Because the distribution is continuous, the probability of generating exactly any single value (including the endpoints 0 and 1) is zero.
As a result, the expression `rand() * 1000 + 41000` produces values from the interval (41000, 42000)—excluding the endpoints. Including the word “inclusive” here could be misleading, unless we intentionally implement a method to ensure inclusion of 41000 or 42000 (e.g., via a mixture model), which does not appear to …

Simple Correction in Captains Log Exercise

---

exercises/concept/name-badges/.docs/hints.md
exercises/concept/name-badges/.docs/instructions.md
exercises/concept/name-badges/runtests.jl

A possible fix for Issue #934 
- exchanged the more specific word `print` for the more general `create` throughout.
- tried to implement backwards compatibility with old solutions, with `exemplar.jl` left with the old function name `print_name_badge` as a test.

create name badge

---

exercises/concept/role-playing-game/.docs/instructions.md

Add blank lines following bullet lists to begin a new paragraph. Omitting this made the instructions for revive in particular hard to understand.
I also felt that the distinction between functions that update the player record and those that only compute values was unclear, so I have tried to make it more obvious.

Some tweaks to the instructions

---

config.json
exercises/concept/problematic-probabilities/.docs/hints.md
exercises/concept/problematic-probabilities/.docs/instructions.md
exercises/concept/problematic-probabilities/.docs/introduction.md
exercises/concept/problematic-probabilities/.meta/config.json
exercises/concept/problematic-probabilities/.meta/design.md
exercises/concept/problematic-probabilities/.meta/exemplar.jl
exercises/concept/problematic-probabilities/problematic-probabilities.jl
exercises/concept/problematic-probabilities/runtests.jl

Here's an idea for an exercise for the `rational-numbers` concept. I've tried to incorporate a realish use case, but this moves it down the syllabus a bit. Some notes:
- Although `vector-operations` seems just as valid, the prereq is listed as `loops`, since this is more general.
- The tests assume that the rounding errors are consistent across Julia and OS versions (and `Float64` is being used for casting).
- Basic probability is used, but also explained.
- `introduction.md` has been pared down quite a bit from the concept version.
I'm unsure if rounding errors will be consistent across Julia and OS versions (but it appears most modern processors are [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754) compliant). In any case, for the examples which have a rounding error, I've tried to …

add concept exercise problematic-probabilities

---

config.json
exercises/practice/flower-field/.docs/instructions.md
exercises/practice/flower-field/.docs/introduction.md
exercises/practice/flower-field/.meta/config.json
exercises/practice/flower-field/.meta/example.jl
exercises/practice/flower-field/.meta/tests.toml
exercises/practice/flower-field/runtests.jl

Deprecates the practice exercise `minesweeper` and replaces it with the practice exercise `flower-field` as per Issue #971 
- `minesweeper` files have been copied over, with all mention of mines being removed.
- Slight updates to the test names have been made to align with `problem-specifications`

deprecate minesweeper, add practice exercise flower-field

---

config.json
exercises/concept/boutique-suggestions/.docs/hints.md
exercises/concept/boutique-suggestions/.docs/instructions.md
exercises/concept/boutique-suggestions/.docs/introduction.md
exercises/concept/boutique-suggestions/.meta/config.json
exercises/concept/boutique-suggestions/.meta/design.md
exercises/concept/boutique-suggestions/.meta/exemplar.jl
exercises/concept/boutique-suggestions/boutique-suggestions.jl
exercises/concept/boutique-suggestions/runtests.jl
exercises/concept/boutique-suggestions/testtools.jl

This is a redesign of `boutique-suggestions` from PR #992. Some notes:
- There are four problems, with all being solvable by different variations of comprehensions (see `exemplar.jl`).
- There are also some added tests to emphasize the column major aspect of Julia (but this will go unnoticed if simple comprehension are used naively).
- Specific concepts from `introduction.md` have been included and referenced in `hints.md`.
- It would be possible to have a final test where all the student's functions are tested in conjunction, but I don't see this as necessary.
- A helper function was used to shorten up `runtests.jl` (and ease modification), but this is not strictly necessary, so explicit `Dict`s can be reintroduced if desired.
- There is an `auxiliary` file used for the helper function, …

add concept exercise boutique-suggestions
